declare const _default: {
    grid: {
        pageWidth: string;
        pageGutter: string;
        pageMain: string;
        page: string;
        2: string;
        3: string;
        4: string;
        5: string;
        6: string;
        7: string;
        8: string;
        9: string;
        10: string;
        11: string;
        12: string;
    };
    color: {
        "grey-50": string;
        "grey-100": string;
        "grey-200": string;
        "grey-300": string;
        "grey-400": string;
        "grey-500": string;
        "grey-600": string;
        "grey-700": string;
        "grey-800": string;
        "grey-900": string;
        black: string;
        grey: string;
        "red-300": string;
        "red-500": string;
        "red-700": string;
        red: string;
        "green-300": string;
        "green-500": string;
        "green-700": string;
        green: string;
        "blue-300": string;
        "blue-500": string;
        "blue-700": string;
        blue: string;
        "pink-300": string;
        "pink-500": string;
        "pink-700": string;
        pink: string;
        "purple-300": string;
        "purple-500": string;
        "purple-700": string;
        purple: string;
        "teal-300": string;
        "teal-500": string;
        "teal-700": string;
        teal: string;
        "yellow-300": string;
        "yellow-500": string;
        "yellow-700": string;
        yellow: string;
        "orange-300": string;
        "orange-500": string;
        "orange-700": string;
        orange: string;
        "brown-300": string;
        "brown-500": string;
        "brown-700": string;
        brown: string;
    };
    radius: {
        xs: string;
        sm: string;
        md: string;
        lg: string;
        xl: string;
        100: string;
        full: string;
    };
    blur: {
        xs: string;
        sm: string;
        md: string;
        lg: string;
        xl: string;
    };
    layer: {
        below: number;
        1: number;
        2: number;
        3: number;
        4: number;
        5: number;
        top: number;
    };
    shadow: {
        xs: string;
        sm: string;
        md: string;
        lg: string;
        xl: string;
    };
    ease: {
        inSine: string;
        outSine: string;
        inOutSine: string;
        inQuad: string;
        outQuad: string;
        inOutQuad: string;
        inCubic: string;
        outCubic: string;
        inOutCubic: string;
        inQuart: string;
        outQuart: string;
        inOutQuart: string;
        inQuint: string;
        outQuint: string;
        inOutQuint: string;
        inExpo: string;
        outExpo: string;
        inOutExpo: string;
        inCirc: string;
        outCirc: string;
        inOutCirc: string;
        inBack: string;
        outBack: string;
        inOutBack: string;
    };
    easing: {
        standard: string;
        accelerate: string;
        decelerate: string;
    };
    elevation: {
        1: string;
        2: string;
        3: string;
        4: string;
        5: string;
        6: string;
        7: string;
    };
    size: {
        px: string;
        1: string;
        2: string;
        3: string;
        4: string;
        5: string;
        6: string;
        7: string;
        8: string;
        9: string;
        10: string;
        11: string;
        12: string;
        14: string;
        16: string;
        20: string;
        24: string;
        28: string;
        32: string;
        36: string;
        40: string;
        44: string;
        48: string;
        52: string;
        56: string;
        60: string;
        64: string;
        72: string;
        80: string;
        96: string;
        full: string;
        screen: string;
        min: string;
        max: string;
    };
    width: {
        xs: string;
        sm: string;
        md: string;
        lg: string;
        xl: string;
    };
    ratio: {
        square: string;
        portrait: string;
        landscape: string;
        tall: string;
        wide: string;
        widescreen: string;
        golden: string;
    };
    scale: {
        "000": string;
        "00": string;
        "0": string;
        "1": string;
        "2": string;
        "3": string;
        "4": string;
        "5": string;
        "6": string;
        "7": string;
        "8": string;
        "9": string;
        "10": string;
    };
    scaleFluid: {
        "000": string;
        "00": string;
        "0": string;
        "1": string;
        "2": string;
        "3": string;
        "4": string;
        "5": string;
        "6": string;
        "7": string;
        "8": string;
        "9": string;
        "10": string;
    };
    font: {
        sans: string;
        serif: string;
        mono: string;
    };
    weight: {
        light: string;
        regular: string;
        medium: string;
        semibold: string;
        bold: string;
        extrabold: string;
        black: string;
    };
    line: {
        none: number;
        xs: number;
        sm: number;
        md: number;
        lg: number;
        xl: number;
    };
    letter: {
        xs: string;
        sm: string;
        none: string;
        lg: string;
        xl: string;
    };
    prose: {
        xs: string;
        sm: string;
        md: string;
        lg: string;
        xl: string;
    };
};
declare const modules: typeof _default;
type ModuleName = keyof typeof modules;
type CustomModule = {
    [rule: string]: {
        [key: string]: string | number;
    };
};
type PollenModule = {
    [module in ModuleName]: {
        [key: string]: string | number;
    };
};
type Query = {
    [query: string]: PollenModule & CustomModule;
};
type ConfigObject = {
    output?: string | {
        css?: string;
        json?: string;
    };
    selector?: string;
    modules: PollenModule & CustomModule;
    media?: Query;
    supports?: Query;
};
type Config = ConfigObject | ((pollen: typeof modules) => ConfigObject);
export { CustomModule, PollenModule, Query, ConfigObject, Config };
